language: go
go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip
install:
  - go get github.com/StefanSchroeder/Golang-Ellipsoid/ellipsoid
matrix:
  allow_failures:
    - go: 1.3
    - go: 1.4
    - go: tip
